### ISSUE TITLE
Module error in the is-promise package

### ISSUE THREAD

**Issue by geoffp** [preactjs-templates/typescript#22]
I can't run this at the moment with either Node v12.16.2 or Node v13.8.0. There seems to be something amiss with `is-promise`.

#### Log for v12.16.2
```
➜  src preact create typescript dog-tracker
internal/modules/cjs/loader.js:1172
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/geoff/.nvm/versions/node/v12.16.2/lib/node_modules/preact-cli/node_modules/is-promise/index.js
require() of ES modules is not supported.
require() of /Users/geoff/.nvm/versions/node/v12.16.2/lib/node_modules/preact-cli/node_modules/is-promise/index.js from /Users/geoff/.nvm/versions/node/v12.16.2/lib/node_modules/preact-cli/node_modules/run-async/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /Users/geoff/.nvm/versions/node/v12.16.2/lib/node_modules/preact-cli/node_modules/is-promise/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/geoff/.nvm/versions/node/v12.16.2/lib/node_modules/preact-cli/node_modules/is-promise/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1172:13)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/geoff/.nvm/versions/node/v12.16.2/lib/node_modules/preact-cli/node_modules/run-async/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14) {
  code: 'ERR_REQUIRE_ESM'
}
```

#### Log for v13.8.0
```
➜  src preact create typescript dog-tracker
internal/modules/cjs/loader.js:635
  throw e;
  ^

Error: No valid exports main found for '/Users/geoff/.nvm/versions/node/v13.8.0/lib/node_modules/preact-cli/node_modules/is-promise'
    at resolveExportsTarget (internal/modules/cjs/loader.js:632:9)
    at applyExports (internal/modules/cjs/loader.js:500:14)
    at resolveExports (internal/modules/cjs/loader.js:549:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:664:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:967:27)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/geoff/.nvm/versions/node/v13.8.0/lib/node_modules/preact-cli/node_modules/run-async/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1151:30) {
  code: 'MODULE_NOT_FOUND'
}
```

### But why?
If I create a project manually with `npm init` and `git init`, and then install `preact-cli` locally there, and then ask about `is-promise` with `npm-why`, I get this:
```
➜  dog-tracker git:(master) ✗ npx npm-why is-promise
npx: installed 4 in 1.177s

  Who required is-promise:

  dog-tracker > preact-cli > inquirer > run-async > is-promise@2.2.0
```

So it looks like `inquirer` is the direct dependency that's goofing us up.

**Comment by geoffp** [comment]
It seems this is an issue with the core CLI, not the template. :)
