### ISSUE TITLE
New project template does not have working Jest config

### ISSUE THREAD

**Issue by pf1gura** [preactjs-templates/typescript#36]
## Issue summary
When creating new project with this template, tests generated for header component do not pass. It seems that TypeScript config is messed up when running Jest, as process errors out on first type declaration in the component 

## Details
```
    SyntaxError: [...]/src/components/header/index.tsx: Unexpected token (5:12)

      3 | import * as style from "./style.css";
      4 |
    > 5 | const Header: FunctionalComponent = () => {
        |             ^
      6 |     return (
      7 |         <header class={style.header}>
      8 |             <h1>Preact App</h1>

      at Object._raise (node_modules/@babel/parser/src/parser/error.js:60:45)
      at Object.raiseWithData (node_modules/@babel/parser/src/parser/error.js:55:17)
      at Object.raise (node_modules/@babel/parser/src/parser/error.js:39:17)
      at Object.unexpected (node_modules/@babel/parser/src/parser/util.js:152:16)
      at Object.parseVar (node_modules/@babel/parser/src/parser/statement.js:1005:18)
      at Object.parseVarStatement (node_modules/@babel/parser/src/parser/statement.js:686:10)
      at Object.parseStatementContent (node_modules/@babel/parser/src/parser/statement.js:209:21)
      at Object.parseStatement (node_modules/@babel/parser/src/parser/statement.js:149:17)
      at Object.parseBlockOrModuleBlockBody (node_modules/@babel/parser/src/parser/statement.js:861:25)
      at Object.parseBlockBody (node_modules/@babel/parser/src/parser/statement.js:833:10)
```

## Steps to reproduce
* `preact create typescript projectName`
* `cd projectName`
* `npm run test`

## Additional information
When creating new project with [widget-typescript](https://github.com/preactjs-templates/widget-typescript) template, Jest tests work just fine, but it seems they have different configuration.

**Comment by Frantss** [comment]
I've managed to fix this by using `ts-jest`, the caveat is that you need to merge the jest preset from `jest-preset-preact` and `ts-jest`.
It works as follows:
``` js
// jest-preset.config.js
const merge = require('merge');
const tsJest = require('ts-jest/jest-preset');
const preactJest = require('jest-preset-preact/jest-preset');

module.exports = {
  ...merge.recursive(tsJest, preactJest),
};

// jest.config.js
module.exports = {
  preset: './jest-preset.config.js',
  ...
}
```

**Comment by Frantss** [comment]
Using `ts-jest` and part of the `jest.config.js` from [`widget-typescript`](https://github.com/preactjs-templates/widget-typescript/blob/master/template/jest.config.js) also works, and it's much cleaner.

``` js
// jest.config.js
module.exports = {
  preset: 'jest-preset-preact',
  transform: {
    '^.+\\.tsx?$': 'ts-jest',
  },
  ...
}
```

**Comment by RyanChristian4427** [comment]
@pf1gura  @Frantss Check if this is now resolved, it should be.

**Comment by pf1gura** [comment]
I can confirm it works now. Thanks!

**Comment by RyanChristian4427** [comment]
Glad to hear it. Feel free to close this if you have no more issues.
