### ISSUE TITLE
New version with fork-ts-checker-webpack-plugin validation error

### ISSUE THREAD

**Issue by ShadiestGoat** [preactjs-templates/typescript#57]
Hey! I started a recent project with this template, and it worked great! I started a new one today, and it doesn't start with the following error:

```
✖ ERROR ValidationError: Invalid configuration object. ForkTsCheckerWebpackPlugin has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property 'silent'. These properties are valid:
   object { async?, typescript?, eslint?, formatter?, issue?, logger? }
    at Object.validate [as default] (/home/shady/Desktop/commisions/Set/site/node_modules/fork-ts-checker-webpack-plugin/node_modules/schema-utils/dist/validate.js:96:11)
    at new ForkTsCheckerWebpackPlugin (/home/shady/Desktop/commisions/Set/site/node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.js:31:31)
    at createBaseConfig (/home/shady/Desktop/commisions/Set/site/node_modules/preact-cli/lib/lib/webpack/webpack-base-config.js:343:7)
    at createClientConfig (/home/shady/Desktop/commisions/Set/site/node_modules/preact-cli/lib/lib/webpack/webpack-client-config.js:321:3)
    at devBuild (/home/shady/Desktop/commisions/Set/site/node_modules/preact-cli/lib/lib/webpack/run-webpack.js:18:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Also the following notices:
```
(node:114136) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /home/shady/Desktop/commisions/Set/site/node_modules/preact/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```
A big difference in the package-lock.json is that the version of `fork-ts-checker-webpack-plugin` is `6.2.10` on today's project, and `4.1.6` on the old one

**Comment by rschristian** [comment]
Noted and fixed, see https://github.com/preactjs/preact-cli/issues/1563

Just need to wait for a new release.

**Comment by ShadiestGoat** [comment]
Yep thanks a lot!

**Comment by rschristian** [comment]
I said it over there on that issue, but you can use your `preact.config.js` to cut out that plugin for now if you wanted to use the updated version, though the downside there would be no type checking from Preact-CLI itself.

Apologies for the issue, hope we can get a new version out soon!
